/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ExampleService_H
#define ExampleService_H

#include <thrift/TDispatchProcessor.h>
#include "example_types.h"

namespace example {

class ExampleServiceIf {
 public:
  virtual ~ExampleServiceIf() {}
  virtual void hello(Message& _return, const Message& m) = 0;
};

class ExampleServiceIfFactory {
 public:
  typedef ExampleServiceIf Handler;

  virtual ~ExampleServiceIfFactory() {}

  virtual ExampleServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ExampleServiceIf* /* handler */) = 0;
};

class ExampleServiceIfSingletonFactory : virtual public ExampleServiceIfFactory {
 public:
  ExampleServiceIfSingletonFactory(const boost::shared_ptr<ExampleServiceIf>& iface) : iface_(iface) {}
  virtual ~ExampleServiceIfSingletonFactory() {}

  virtual ExampleServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ExampleServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<ExampleServiceIf> iface_;
};

class ExampleServiceNull : virtual public ExampleServiceIf {
 public:
  virtual ~ExampleServiceNull() {}
  void hello(Message& /* _return */, const Message& /* m */) {
    return;
  }
};

typedef struct _ExampleService_hello_args__isset {
  _ExampleService_hello_args__isset() : m(false) {}
  bool m;
} _ExampleService_hello_args__isset;

class ExampleService_hello_args {
 public:

  ExampleService_hello_args() {
  }

  virtual ~ExampleService_hello_args() throw() {}

  Message m;

  _ExampleService_hello_args__isset __isset;

  void __set_m(const Message& val) {
    m = val;
  }

  bool operator == (const ExampleService_hello_args & rhs) const
  {
    if (!(m == rhs.m))
      return false;
    return true;
  }
  bool operator != (const ExampleService_hello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ExampleService_hello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ExampleService_hello_pargs {
 public:


  virtual ~ExampleService_hello_pargs() throw() {}

  const Message* m;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ExampleService_hello_result__isset {
  _ExampleService_hello_result__isset() : success(false) {}
  bool success;
} _ExampleService_hello_result__isset;

class ExampleService_hello_result {
 public:

  ExampleService_hello_result() {
  }

  virtual ~ExampleService_hello_result() throw() {}

  Message success;

  _ExampleService_hello_result__isset __isset;

  void __set_success(const Message& val) {
    success = val;
  }

  bool operator == (const ExampleService_hello_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ExampleService_hello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ExampleService_hello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ExampleService_hello_presult__isset {
  _ExampleService_hello_presult__isset() : success(false) {}
  bool success;
} _ExampleService_hello_presult__isset;

class ExampleService_hello_presult {
 public:


  virtual ~ExampleService_hello_presult() throw() {}

  Message* success;

  _ExampleService_hello_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ExampleServiceClient : virtual public ExampleServiceIf {
 public:
  ExampleServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ExampleServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void hello(Message& _return, const Message& m);
  void send_hello(const Message& m);
  void recv_hello(Message& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ExampleServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ExampleServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ExampleServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_hello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ExampleServiceProcessor(boost::shared_ptr<ExampleServiceIf> iface) :
    iface_(iface) {
    processMap_["hello"] = &ExampleServiceProcessor::process_hello;
  }

  virtual ~ExampleServiceProcessor() {}
};

class ExampleServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ExampleServiceProcessorFactory(const ::boost::shared_ptr< ExampleServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ExampleServiceIfFactory > handlerFactory_;
};

class ExampleServiceMultiface : virtual public ExampleServiceIf {
 public:
  ExampleServiceMultiface(std::vector<boost::shared_ptr<ExampleServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ExampleServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ExampleServiceIf> > ifaces_;
  ExampleServiceMultiface() {}
  void add(boost::shared_ptr<ExampleServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void hello(Message& _return, const Message& m) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->hello(_return, m);
    }
    ifaces_[i]->hello(_return, m);
    return;
  }

};

} // namespace

#endif
