# Generated by Erlang.mk. Edit at your own risk!

src/exampleService_thrift.erl:: src/exampleService_thrift.hrl src/example_types.hrl; @touch $@
src/example_types.erl:: src/example_types.hrl; @touch $@
src/thrift_handle.erl:: src/exampleService_thrift.hrl src/example_types.hrl; @touch $@

COMPILE_FIRST +=
