PROJECT = erl_sample
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy 
dep_cowboy_commit = 2.6.1
#DEP_PLUGINS =  cowboy 

DEPS += thrift
dep_thrift = git https://github.com/j14159/thrift 0.9.1
DEP_PLUGINS =  cowboy, thrift

include erlang.mk
